/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "dashboard": [],
    "sidang.index": [],
    "sidang.create": [],
    "sidang.store": [],
    "sidang.show": [
        {
            "name": "sidang",
            "required": true,
            "binding": "id"
        }
    ],
    "sidang.edit": [
        {
            "name": "sidang",
            "required": true,
            "binding": "id"
        }
    ],
    "sidang.update": [
        {
            "name": "sidang",
            "required": true,
            "binding": "id"
        }
    ],
    "sidang.destroy": [
        {
            "name": "sidang",
            "required": true,
            "binding": "id"
        }
    ],
    "sidang.jadwal.store": [
        {
            "name": "sidang",
            "required": true,
            "binding": "id"
        }
    ],
    "sidang.jadwal.update": [
        {
            "name": "sidang",
            "required": true,
            "binding": "id"
        }
    ],
    "undangan.dosen-schedules": [],
    "undangan.index": [],
    "undangan.create": [],
    "undangan.store": [],
    "undangan.show": [
        {
            "name": "undangan",
            "required": true,
            "binding": "id"
        }
    ],
    "undangan.destroy": [
        {
            "name": "undangan",
            "required": true,
            "binding": "id"
        }
    ],
    "undangan.preview": [
        {
            "name": "undangan",
            "required": true,
            "binding": "id"
        }
    ],
    "undangan.download": [
        {
            "name": "undangan",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.dashboard": [],
    "admin.users.index": [],
    "admin.users.create": [],
    "admin.users.store": [],
    "admin.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.dosen.index": [],
    "admin.dosen.create": [],
    "admin.dosen.store": [],
    "admin.dosen.edit": [
        {
            "name": "dosen",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.dosen.update": [
        {
            "name": "dosen",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.dosen.destroy": [
        {
            "name": "dosen",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.dosen.bulk.create": [],
    "admin.dosen.bulk.store": [],
    "admin.dosen.bulk.template": [],
    "admin.mahasiswa.index": [],
    "admin.mahasiswa.create": [],
    "admin.mahasiswa.store": [],
    "admin.mahasiswa.edit": [
        {
            "name": "mahasiswa",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.mahasiswa.update": [
        {
            "name": "mahasiswa",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.mahasiswa.destroy": [
        {
            "name": "mahasiswa",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.mahasiswa.bulk.create": [],
    "admin.mahasiswa.bulk.store": [],
    "admin.mahasiswa.bulk.template": [],
    "admin.pic.index": [],
    "admin.pic.create": [],
    "admin.pic.store": [],
    "admin.pic.edit": [
        {
            "name": "pic",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.pic.update": [
        {
            "name": "pic",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.pic.destroy": [
        {
            "name": "pic",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.pic.bulk.create": [],
    "admin.pic.bulk.store": [],
    "admin.pic.bulk.template": [],
    "admin.program-studi.index": [],
    "admin.program-studi.create": [],
    "admin.program-studi.store": [],
    "admin.program-studi.edit": [
        {
            "name": "program_studi",
            "required": true
        }
    ],
    "admin.program-studi.update": [
        {
            "name": "program_studi",
            "required": true
        }
    ],
    "admin.program-studi.destroy": [
        {
            "name": "program_studi",
            "required": true
        }
    ],
    "admin.program-studi.bulk.create": [],
    "admin.program-studi.bulk.store": [],
    "admin.program-studi.bulk.template": [],
    "admin.sidang.index": [],
    "admin.sidang.bulk.create": [],
    "admin.sidang.bulk.store": [],
    "admin.sidang.bulk.template": [],
    "admin.sidang.show": [
        {
            "name": "sidang",
            "required": true,
            "binding": "id"
        }
    ],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
